import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Gerenciador de Hábitos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} flex flex-col items-center justify-center bg-zinc-900 pt-8 text-white antialiased`}
      >
        <Image src="/images/logo.svg" width={240} height={240} alt="Logo" />
        {children}
      </body>
    </html>
  );
}
